
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Marco Jose
 */
public class jfrmPrestamo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfrmPrestamo.class.getName());

    /**
     * Creates new form jfrmPrestamo
     */
    public jfrmPrestamo() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setSize(485, 395);
        
         
      
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jMenu3 = new javax.swing.JMenu();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jMenuItem3 = new javax.swing.JMenuItem();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtablaPrestamo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jtfCredito = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfPeriodoMax = new javax.swing.JTextField();
        jtfPeriodoMin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfInteresMax = new javax.swing.JTextField();
        jtfInteresMin = new javax.swing.JTextField();
        jcbIncremento = new javax.swing.JComboBox<>();
        jbtCalculoPagos = new javax.swing.JButton();
        jbtCalculoAmort = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmItemAños = new javax.swing.JMenuItem();
        jmItemMeses = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jLabel1.setText("jLabel1");
        jScrollPane1.setViewportView(jLabel1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prestamo Bancario");
        setResizable(false);

        jtablaPrestamo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "29 años", "30 años"
            }
        ));
        jtablaPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablaPrestamoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jtablaPrestamo);

        jLabel2.setText("Credito:");

        jLabel3.setText("Años del prestamno");

        jLabel4.setText("Maximo:");

        jLabel5.setText("Minimo:");

        jLabel6.setText("Tipos de interes");

        jLabel7.setText("% maximo:");

        jLabel8.setText("% minimo:");

        jLabel9.setText("Incremento");

        jtfInteresMax.addActionListener(this::jtfInteresMaxActionPerformed);

        jcbIncremento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.50", "1" }));
        jcbIncremento.setSelectedItem(0.50);

        jbtCalculoPagos.setText("Pagos");
        jbtCalculoPagos.addActionListener(this::jbtCalculoPagosActionPerformed);

        jbtCalculoAmort.setText("Amortizacion");
        jbtCalculoAmort.addActionListener(this::jbtCalculoAmortActionPerformed);

        jMenu1.setMnemonic('o');
        jMenu1.setText("Opciones");

        jMenuItem1.setText("Instrucciones");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator2);

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('p');
        jMenu2.setText("Prestamo en...");

        jmItemAños.setText("Años");
        jmItemAños.addActionListener(this::jmItemAñosActionPerformed);
        jMenu2.add(jmItemAños);

        jmItemMeses.setText("Meses");
        jmItemMeses.addActionListener(this::jmItemMesesActionPerformed);
        jMenu2.add(jmItemMeses);

        jMenuBar1.add(jMenu2);

        jMenu4.setMnemonic('a');
        jMenu4.setText("Ayuda");

        jMenuItem5.setText("Acerca de");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Comentarios");

        jMenuItem4.setText("Comentario");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu5.add(jMenuItem4);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtfPeriodoMax)
                                .addComponent(jtfPeriodoMin)))
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfInteresMax))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jcbIncremento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfInteresMin))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jbtCalculoAmort, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                        .addComponent(jbtCalculoPagos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfPeriodoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfPeriodoMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtfInteresMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jtfInteresMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jcbIncremento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtCalculoPagos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtCalculoAmort))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jtfInteresMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfInteresMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfInteresMaxActionPerformed

    private void jmItemAñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemAñosActionPerformed
        // TODO add your handling code here:
         setTitle("Préstamo Bancario - Años");

        jmItemAños.setEnabled(false);
        jmItemMeses.setEnabled(true);
    }//GEN-LAST:event_jmItemAñosActionPerformed

    private void jmItemMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemMesesActionPerformed
        // TODO add your handling code here:
        setTitle("Préstamo Bancario - Meses");

        jmItemAños.setEnabled(true);
        jmItemMeses.setEnabled(false);
    }//GEN-LAST:event_jmItemMesesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this,
        "PRÉSTAMO BANCARIO\n\n"
        + "1. Ingrese el monto del crédito.\n"
        + "2. Ingrese el período mínimo y máximo.\n"
        + "3. Ingrese el interés mínimo y máximo.\n"
        + "4. Seleccione el incremento de tasa.\n"
        + "5. Presione CALCULAR PAGOS.\n"
        + "6. Seleccione una cuota de la tabla.\n"
        + "7. Presione AMORTIZACIÓN para ver el desglose.",
        "Instrucciones",
        JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jbtCalculoPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCalculoPagosActionPerformed
        // TODO add your handling code here:
        try {

        double credito = Double.parseDouble(jtfCredito.getText());
        int periodoMin = Integer.parseInt(jtfPeriodoMin.getText());
        int periodoMax = Integer.parseInt(jtfPeriodoMax.getText());

        double interesMin = Double.parseDouble(jtfInteresMin.getText());
        double interesMax = Double.parseDouble(jtfInteresMax.getText());

        double incremento = Double.parseDouble(
                jcbIncremento.getSelectedItem().toString()
        );

        
        if (credito <= 0) {
            JOptionPane.showMessageDialog(this,
                    "El monto del crédito debe ser mayor que 0.");
            return;
        }

        if (periodoMin <= 0 || periodoMax < periodoMin) {
            JOptionPane.showMessageDialog(this,
                    "Verifique el rango de períodos.");
            return;
        }

        if (interesMin < 0 || interesMax < interesMin) {
            JOptionPane.showMessageDialog(this,
                    "Verifique el rango de intereses.");
            return;
        }

        if (incremento <= 0) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione un incremento válido.");
            return;
        }

   
        DefaultTableModel modelo =
                (DefaultTableModel) jtablaPrestamo.getModel();

        modelo.setRowCount(0);

      
        modelo.setColumnCount(0);

        modelo.addColumn("Período");

    
        int cantidadTasas =
                (int) Math.round((interesMax - interesMin) / incremento) + 1;

        for (int i = 0; i < cantidadTasas; i++) {

            double tasa = interesMin + (i * incremento);

            modelo.addColumn(
                    String.format("%.2f%%", tasa)
            );
        }

        
        for (int periodo = periodoMin;
                periodo <= periodoMax;
                periodo++) {

            Object[] fila = new Object[cantidadTasas + 1];

            fila[0] = periodo;

            for (int i = 0; i < cantidadTasas; i++) {

                double tasa =
                        interesMin + (i * incremento);

                double tasaDecimal = tasa / 100.0;

                
                double tasaMensual = tasaDecimal / 12.0;

                int meses;
                boolean enAnios = false;

                if (enAnios) {
                    meses = periodo * 12;
                } else {
                    meses = periodo;
                }

                double cuota;

                if (tasaMensual == 0) {

                    cuota = credito / meses;

                } else {

                    cuota = credito *
                            (tasaMensual *
                            Math.pow(1 + tasaMensual, meses))
                            /
                            (Math.pow(1 + tasaMensual, meses) - 1);
                }

                fila[i + 1] = String.format("%.2f", cuota);
            }

            modelo.addRow(fila);
        }

        // Actualizar tabla
        jtablaPrestamo.setModel(modelo);

        JOptionPane.showMessageDialog(this,
                "Los pagos fueron calculados correctamente.");

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(this,
                "Ingrese valores numéricos válidos.");
    }
    }//GEN-LAST:event_jbtCalculoPagosActionPerformed

    private void jtablaPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaPrestamoMouseClicked
        // TODO add your handling code here:
         int fila = jtablaPrestamo.getSelectedRow();
    int columna = jtablaPrestamo.getSelectedColumn();

    if (fila >= 0 && columna > 0) {
        jbtCalculoAmort.setEnabled(true);
    } else {
        jbtCalculoAmort.setEnabled(false);
    }
    }//GEN-LAST:event_jtablaPrestamoMouseClicked

    private void jbtCalculoAmortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCalculoAmortActionPerformed
        // TODO add your handling code here:
         calcularAmortizacion();
         jbtCalculoAmortActionPerformed();
    }//GEN-LAST:event_jbtCalculoAmortActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Programa Creado Por Marco Jose Castillo Mejia de IVD", "Comentarios", HEIGHT);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfrmPrestamo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JButton jbtCalculoAmort;
    private javax.swing.JButton jbtCalculoPagos;
    private javax.swing.JComboBox<String> jcbIncremento;
    private javax.swing.JMenuItem jmItemAños;
    private javax.swing.JMenuItem jmItemMeses;
    private javax.swing.JTable jtablaPrestamo;
    private javax.swing.JTextField jtfCredito;
    private javax.swing.JTextField jtfInteresMax;
    private javax.swing.JTextField jtfInteresMin;
    private javax.swing.JTextField jtfPeriodoMax;
    private javax.swing.JTextField jtfPeriodoMin;
    // End of variables declaration//GEN-END:variables

    private void calcularAmortizacion() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void jbtCalculoAmortActionPerformed() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
